const APP_VERSION='vitoriaware-pilot-1';
const STATE_KEY='voetupper-vitoriaware-state-v1';
const AUTH_KEY='voetupper-vitoriaware-auth-v1';
const SESSION_KEY='voetupper-vitoriaware-session-v1';
const MASTER_HANDLE='empresaria01-teste-master';
const PORTAL_URL='https://pedidos.tupperware.com.br/grandevitoria/Default.aspx';
const weeks=[
 {week:'35/2026',vitrine:'08/2026',start:'2026-08-24',end:'2026-08-30'},
 {week:'36/2026',vitrine:'09/2026',start:'2026-08-31',end:'2026-09-06'},
 {week:'37/2026',vitrine:'09/2026',start:'2026-09-07',end:'2026-09-13'},
 {week:'38/2026',vitrine:'09/2026',start:'2026-09-14',end:'2026-09-20'},
 {week:'39/2026',vitrine:'09/2026',start:'2026-09-21',end:'2026-09-27'}
];
let view='today';let modal=null;let installPrompt=null;
function freshState(){return{workspace:{name:'Empresária Serra',distribution:'Vitoriaware',region:'Serra / Espírito Santo',goal:0},consultants:[],orders:[]}}
function loadState(){try{const parsed=JSON.parse(localStorage.getItem(STATE_KEY));if(parsed&&parsed.workspace&&Array.isArray(parsed.consultants)&&Array.isArray(parsed.orders))return parsed}catch{}return freshState()}
let state=loadState();
function save(){localStorage.setItem(STATE_KEY,JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtMoney(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)}
function localDate(){return new Date(new Date().toLocaleString('en-US',{timeZone:'America/Sao_Paulo'}))}
function activeCycle(){const now=localDate();const y=now.getFullYear(),m=String(now.getMonth()+1).padStart(2,'0'),d=String(now.getDate()).padStart(2,'0');const iso=`${y}-${m}-${d}`;return weeks.find(w=>iso>=w.start&&iso<=w.end)||weeks[0]}
function closingLabel(c=activeCycle()){const today=localDate();const y=today.getFullYear(),m=String(today.getMonth()+1).padStart(2,'0'),d=String(today.getDate()).padStart(2,'0');const iso=`${y}-${m}-${d}`;if(iso===c.end)return'FECHAMENTO HOJE';if(iso>c.end)return'ENCERRADA';const end=new Date(`${c.end}T12:00:00`);const diff=Math.ceil((end-today)/86400000);return diff<=1?'FECHA AMANHÃ':`FECHA EM ${diff} DIAS`}
function nextAction(o){if(o.cancelled)return'Sem ação';if(o.finalized)return'Concluído';if(o.print)return'Finalizar / confirmar';if(o.portal)return'Enviar print';if(o.checked)return'Lançar no portal';return'Conferir pedido'}
function status(o){if(o.cancelled)return'CANCELADO';if(o.finalized)return'FINALIZADO';if(o.print)return'PRINT ENVIADO';if(o.portal)return'NO PORTAL';if(o.checked)return'CONFERIDO';return'RECEBIDO'}
function pendingOrders(){return state.orders.filter(o=>!o.cancelled&&!o.finalized)}
function currentOrders(){const c=activeCycle();return state.orders.filter(o=>o.week===c.week)}
function stats(){const orders=currentOrders().filter(o=>!o.cancelled);const pending=orders.filter(o=>!o.finalized);const ordered=new Set(orders.map(o=>o.consultantId));const active=state.consultants.filter(c=>c.status!=='INATIVA');return{pending:pending.length,noOrder:Math.max(0,active.length-ordered.size),portal:pending.filter(o=>o.checked&&!o.portal).length,print:pending.filter(o=>o.portal&&!o.print).length,revenue:orders.reduce((s,o)=>s+(Number(o.amount)||0),0),done:orders.filter(o=>o.finalized).length}}
function initials(name){return(name||'?').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()}
async function hashSecret(secret,salt){const bytes=new TextEncoder().encode(`${salt}:${secret}`);const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function authRecord(){try{return JSON.parse(localStorage.getItem(AUTH_KEY))}catch{return null}}
function isSignedIn(){return sessionStorage.getItem(SESSION_KEY)==='1'}
function validNewPassword(p){return p.length>=8&&/[A-Za-z]/.test(p)&&/[^A-Za-z\s]/.test(p)&&!/^[0-9]+$/.test(p)}
function renderLogin(){const exists=!!authRecord();document.getElementById('root').innerHTML=`<div class="login-wrap"><section class="login-brand"><div><img src="logo.svg?v=4" alt=""><h1>VoeTupper</h1><p>Operação Vitoriaware em um só lugar: pedidos, fechamento, equipe e próxima ação.</p></div><div class="login-note">Piloto Vitoriaware · Espírito Santo · ${APP_VERSION}</div></section><section class="login-panel"><form class="login-card" id="loginForm"><h2>${exists?'Entrar':'Primeiro acesso'}</h2><p>${exists?'Use seu acesso do piloto.':'Crie uma senha local para proteger este piloto neste dispositivo.'}</p><div class="field"><label>Usuária</label><input id="loginHandle" value="${MASTER_HANDLE}" autocomplete="username" required></div><div class="field"><label>${exists?'Senha':'Criar senha'}</label><input id="loginPassword" type="password" autocomplete="${exists?'current-password':'new-password'}" required></div>${!exists?'<p class="helper">Não use CPF, telefone nem senha do Tupper.NET. Para o produto real, o acesso migrará para link seguro por e-mail.</p>':''}<div class="error" id="loginError"></div><button class="btn primary full">${exists?'Entrar':'Criar acesso do piloto'}</button></form></section></div>`;document.getElementById('loginForm').addEventListener('submit',handleLogin)}
async function handleLogin(e){e.preventDefault();const handle=document.getElementById('loginHandle').value.trim().toLowerCase();const password=document.getElementById('loginPassword').value;const error=document.getElementById('loginError');if(handle!==MASTER_HANDLE){error.textContent='Usuária não reconhecida neste piloto.';return}const current=authRecord();if(!current){if(!validNewPassword(password)){error.textContent='Use pelo menos 8 caracteres, com letra e símbolo. Não use CPF ou telefone.';return}const salt=crypto.randomUUID();const hash=await hashSecret(password,salt);localStorage.setItem(AUTH_KEY,JSON.stringify({handle,salt,hash}));sessionStorage.setItem(SESSION_KEY,'1');render();return}const hash=await hashSecret(password,current.salt);if(hash!==current.hash){error.textContent='Senha incorreta.';return}sessionStorage.setItem(SESSION_KEY,'1');render()}
function signOut(){sessionStorage.removeItem(SESSION_KEY);render()}
function nav(){return[['today','Hoje'],['orders','Pedidos'],['closing','Fechamento'],['team','Equipe']].map(([id,label])=>`<button class="${view===id?'active':''}" onclick="go('${id}')">${label}</button>`).join('')}
function shell(content){const c=activeCycle();const s=stats();return`<div class="app-shell"><aside class="sidebar"><div class="brand-row"><img src="logo.svg?v=4" alt=""><div class="brand-name">VoeTupper<small>operação Vitoriaware</small></div></div><div class="workspace-badge"><strong>${esc(state.workspace.name)}</strong><span>${esc(state.workspace.region)}</span></div><nav class="nav">${nav()}</nav><div class="sidebar-foot"><div class="sync">Base piloto: planilha-template preparada<br>Sincronização privada: próxima etapa segura</div><button class="btn" onclick="signOut()">Sair</button></div></aside><main class="main"><header class="topbar"><div class="cycle"><strong>${esc(state.workspace.name)}</strong><span class="cycle-chip" data-cycle="vitrine">Vitrine ${c.vitrine}</span><span class="cycle-chip" data-cycle="semana">Semana ${c.week}</span><span class="cycle-chip alert">${closingLabel(c)}</span></div><div class="top-actions"><button class="btn secondary-desktop" id="installBtn" onclick="installApp()">Instalar PWA</button><button class="btn primary" onclick="openOrder()">+ Novo pedido</button></div></header><div class="content">${content}</div></main><nav class="mobile-nav">${nav()}</nav>${modal||''}</div>`}
function quickActions(){const s=stats();return`<div class="quick-actions"><button class="quick" onclick="openOrder()"><div><strong>+ Novo pedido</strong><span>Semana e data automáticas</span></div><b class="arrow">›</b></button><button class="quick" onclick="go('closing')"><div><strong>Fechamento</strong><span>${s.pending} pendência${s.pending===1?'':'s'}</span></div><b class="arrow">›</b></button><button class="quick" onclick="window.open(PORTAL_URL,'_blank')"><div><strong>Abrir portal</strong><span>Tupper.NET</span></div><b class="arrow">↗</b></button><button class="quick" onclick="go('team')"><div><strong>Equipe</strong><span>Buscar código e contato</span></div><b class="arrow">›</b></button></div>`}
function queueRow(o,index){const c=state.consultants.find(x=>x.id===o.consultantId);const name=c?.name||'Consultora';const action=nextAction(o);return`<div class="queue-row"><span class="priority">${index+1}</span><div><div class="queue-name">${esc(name)}</div><div class="queue-meta">${esc(o.summary)}${o.amount?` · ${fmtMoney(o.amount)}`:''} · ${status(o)}</div></div><div class="next-action">${action}</div><div class="queue-actions">${!o.checked?`<button class="mini primary" data-action="conferir" onclick="setStep('${o.id}','checked')">Conferir</button>`:!o.portal?`<button class="mini primary" data-action="portal" onclick="setStep('${o.id}','portal')">Portal</button>`:!o.print?`<button class="mini primary" data-action="print" onclick="setStep('${o.id}','print')">Print</button>`:!o.finalized?`<button class="mini primary" data-action="finalizar" onclick="setStep('${o.id}','finalized')">Finalizar</button>`:''}<button class="mini danger" data-action="cancelar" onclick="cancelOrder('${o.id}')">Cancelar</button></div></div>`}
function queuePanel(){const p=pendingOrders();return`<section class="panel queue" data-ui="work-queue"><div class="panel-head"><h2>Ação agora</h2><small>Próxima ação</small></div>${p.length?p.map(queueRow).join(''):`<div class="queue-empty"><strong>Nada pendente agora.</strong>Quando chegar um pedido, ele entra aqui já com a próxima ação.</div>`}</section>`}
function summaryPanel(){const s=stats();const goal=Number(state.workspace.goal)||0;const pct=goal?Math.min(100,Math.round(s.revenue/goal*100)):0;return`<section class="panel"><div class="panel-head"><h2>O que precisa ser resolvido</h2></div><div class="summary"><div class="metric"><strong>${s.pending}</strong><span>Pedidos pendentes</span></div><div class="metric"><strong>${s.noOrder}</strong><span>Sem pedido</span></div><div class="metric"><strong>${s.portal}</strong><span>Portal</span></div><div class="metric"><strong>${s.print}</strong><span>Print</span></div></div><div class="money-block"><div class="helper">Faturamento da semana</div><div class="amount">${fmtMoney(s.revenue)}</div><div class="progress"><i style="width:${pct}%"></i></div><div class="progress-meta"><span>${goal?`Meta ${fmtMoney(goal)}`:'Meta não informada'}</span><span>${goal?`${pct}%`:''}</span></div><button class="btn linklike" onclick="editGoal()">${goal?'Alterar meta':'Definir meta'}</button></div></section>`}
function recentOrders(){const rows=currentOrders().slice().reverse().slice(0,6);return`<section class="panel"><div class="panel-head"><h2>Pedidos recentes</h2><button class="btn" onclick="go('orders')">Ver todos</button></div><div class="table-wrap"><div class="order-head"><span>Consultora</span><span>Status</span><span>Valor</span><span>Próxima ação</span><span></span></div>${rows.length?rows.map(o=>{const c=state.consultants.find(x=>x.id===o.consultantId);return`<div class="order-row"><strong>${esc(c?.name||'Consultora')}</strong><span class="status ${o.finalized?'done':''}">${status(o)}</span><span>${o.amount?fmtMoney(o.amount):'—'}</span><span>${nextAction(o)}</span><button class="mini" onclick="go('closing')">Abrir</button></div>`}).join(''):`<div class="queue-empty">Nenhum pedido ainda.</div>`}</div></section>`}
function weeksPanel(){return`<section class="panel"><div class="panel-head"><h2>Semanas</h2><small>Vitrine ≠ Semana</small></div><div class="week-list">${weeks.slice(0,4).map(w=>`<div class="week-row"><strong>Semana ${w.week}</strong><div>${w.start.split('-').reverse().join('/')} a ${w.end.split('-').reverse().join('/')} · Vitrine ${w.vitrine} · ${closingLabel(w)}</div></div>`).join('')}</div></section>`}
function today(){return`${quickActions()}<div class="section-label">O que precisa ser resolvido</div><div class="ops-grid">${queuePanel()}${summaryPanel()}</div><div class="lower-grid">${recentOrders()}${weeksPanel()}</div>`}
function ordersView(){const rows=state.orders.slice().reverse();return`<section class="panel"><div class="panel-head"><h2>Pedidos</h2><button class="btn primary" onclick="openOrder()">+ Novo pedido</button></div><div class="table-wrap"><div class="order-head"><span>Consultora</span><span>Status</span><span>Valor</span><span>Próxima ação</span><span></span></div>${rows.length?rows.map(o=>{const c=state.consultants.find(x=>x.id===o.consultantId);return`<div class="order-row"><strong>${esc(c?.name||'Consultora')}</strong><span class="status ${o.finalized?'done':''}">${status(o)}</span><span>${o.amount?fmtMoney(o.amount):'—'}</span><span>${nextAction(o)}</span><button class="mini" onclick="go('closing')">Abrir</button></div>`}).join(''):`<div class="queue-empty">Nenhum pedido cadastrado.</div>`}</div></section>`}
function closingView(){return`${quickActions()}<div class="section-label">Fechamento da semana</div>${queuePanel()}`}
function teamView(){return`<section class="panel"><div class="panel-head"><h2>Equipe</h2><button class="btn primary" onclick="openPerson()">+ Consultora</button></div><div class="team-toolbar"><input class="search" id="teamSearch" placeholder="Pesquisar nome, código ou telefone" oninput="renderTeamRows(this.value)"></div><div id="teamRows">${teamRows('')}</div></section>`}
function teamRows(q){const needle=q.trim().toLowerCase();const list=state.consultants.filter(c=>!needle||[c.name,c.code,c.phone].some(v=>(v||'').toLowerCase().includes(needle)));return list.length?list.map(c=>`<div class="team-row"><strong>${esc(c.name)}</strong><span>${esc(c.code||'—')}</span><span class="mobile-hide">${esc(c.phone||'—')}</span><span class="mobile-hide">${esc(c.status||'ATIVA')}</span><div>${c.phone?`<a class="btn" style="text-decoration:none;display:inline-grid;place-items:center" href="https://wa.me/55${c.phone.replace(/\D/g,'')}" target="_blank">WhatsApp</a>`:''}</div></div>`).join(''):`<div class="queue-empty">Nenhuma consultora encontrada.</div>`}
function renderTeamRows(q){document.getElementById('teamRows').innerHTML=teamRows(q)}
function render(){if(!isSignedIn()){renderLogin();return}const content=view==='today'?today():view==='orders'?ordersView():view==='closing'?closingView():teamView();document.getElementById('root').innerHTML=shell(content);if(!installPrompt){const b=document.getElementById('installBtn');if(b)b.style.display='none'}}
function go(v){view=v;modal=null;render()}
function setStep(id,key){state.orders=state.orders.map(o=>o.id===id?{...o,[key]:true}:o);save();render()}
function cancelOrder(id){if(!confirm('Cancelar este pedido?'))return;state.orders=state.orders.map(o=>o.id===id?{...o,cancelled:true}:o);save();render()}
function editGoal(){const current=Number(state.workspace.goal)||0;const raw=prompt('Meta da equipe para a semana (R$):',current||'');if(raw===null)return;const value=Number(raw.replace(/\./g,'').replace(',','.'));if(!Number.isFinite(value)||value<0)return alert('Meta inválida.');state.workspace.goal=value;save();render()}
function openOrder(){if(!state.consultants.length){alert('Cadastre ao menos uma consultora primeiro.');go('team');return}const c=activeCycle();modal=`<div class="sheet"><form class="sheet-card" id="orderForm"><div class="sheet-head"><div><h2>Novo pedido</h2><div class="context-note">Vitrine ${c.vitrine} · Semana ${c.week} · data automática</div></div><button type="button" class="btn" onclick="closeModal()">Fechar</button></div><div class="form-grid"><div class="field span2"><label>Consultora</label><select id="oConsultant" required>${state.consultants.filter(x=>x.status!=='INATIVA').map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Recebi por</label><select id="oSource"><option>WhatsApp texto</option><option>WhatsApp áudio</option><option>Foto</option><option>Ligação</option><option>Outro</option></select></div><div class="field"><label>Pagamento</label><select id="oPayment"><option value="">Não informado</option><option>PIX</option><option>BOLETO</option><option>CARTÃO</option><option>DINHEIRO</option></select></div><div class="field span2"><label>Resumo / itens</label><textarea id="oSummary" required placeholder="Ex.: 2 caixas ideal + 1 garrafa"></textarea></div><div class="field"><label>Qtd.</label><input id="oQty" inputmode="numeric" type="number" min="1"></div><div class="field"><label>Valor</label><input id="oAmount" inputmode="decimal" placeholder="0,00"></div><div class="field span2"><label>Observação</label><input id="oNote" placeholder="Opcional"></div></div><div class="error" id="orderError"></div><div class="form-actions"><button type="button" class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar pedido</button></div></form></div></div>`;render();document.getElementById('orderForm').addEventListener('submit',saveOrder)}
function saveOrder(e){e.preventDefault();const raw=document.getElementById('oAmount').value.trim();let amount=0;if(raw){amount=Number(raw.replace(/\./g,'').replace(',','.'));if(!Number.isFinite(amount)||amount<0){document.getElementById('orderError').textContent='Valor inválido.';return}}const c=activeCycle();state.orders.push({id:crypto.randomUUID(),vitrine:c.vitrine,week:c.week,consultantId:document.getElementById('oConsultant').value,date:new Date().toISOString(),source:document.getElementById('oSource').value,summary:document.getElementById('oSummary').value.trim(),qty:Number(document.getElementById('oQty').value)||0,amount,payment:document.getElementById('oPayment').value,note:document.getElementById('oNote').value.trim(),checked:false,portal:false,print:false,finalized:false,cancelled:false});save();modal=null;view='today';render()}
function openPerson(){modal=`<div class="sheet"><form class="sheet-card" id="personForm"><div class="sheet-head"><h2>Nova consultora</h2><button type="button" class="btn" onclick="closeModal()">Fechar</button></div><div class="form-grid"><div class="field span2"><label>Nome</label><input id="pName" required minlength="2"></div><div class="field"><label>Código</label><input id="pCode"></div><div class="field"><label>Telefone</label><input id="pPhone" inputmode="tel"></div><div class="field"><label>Situação</label><select id="pStatus"><option>ATIVA</option><option>NOVA</option><option>PAUSADA</option><option>INATIVA</option></select></div><div class="field"><label>Responsável / Líder</label><input id="pLeader"></div></div><p class="helper">Senha do Tupper.NET não é armazenada no VoeTupper.</p><div class="form-actions"><button type="button" class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary">Adicionar</button></div></form></div></div>`;render();document.getElementById('personForm').addEventListener('submit',savePerson)}
function savePerson(e){e.preventDefault();state.consultants.push({id:crypto.randomUUID(),name:document.getElementById('pName').value.trim(),code:document.getElementById('pCode').value.trim(),phone:document.getElementById('pPhone').value.trim(),status:document.getElementById('pStatus').value,leader:document.getElementById('pLeader').value.trim()});save();modal=null;view='team';render()}
function closeModal(){modal=null;render()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;render()});async function installApp(){if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;render()}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
