const HOTFIX_VERSION='2026-09-03.1';
const HOTFIX_TEAM_KEY='voetupper-team-import-key-v2';

try{if(Array.isArray(weeks)){const w35=weeks.find(w=>w.week==='35/2026');if(w35)w35.vitrine='09/2026'}}catch(e){console.error(e)}
function hotfixB64urlBytes(value){const pad='='.repeat((4-value.length%4)%4);const bin=atob(value.replace(/-/g,'+').replace(/_/g,'/')+pad);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
function getTeamImportKey(){const match=location.hash.match(/(?:^#|&)team=([^&]+)/);if(match){const key=decodeURIComponent(match[1]);sessionStorage.setItem(HOTFIX_TEAM_KEY,key);return key}return sessionStorage.getItem(HOTFIX_TEAM_KEY)||sessionStorage.getItem('voetupper-team-import-key-v1')}
async function hotfixDecryptTeam(keyText){const response=await fetch('./team.enc.json?v=4',{cache:'no-store'});if(!response.ok)throw new Error(`Equipe indisponível (${response.status})`);const payload=await response.json();const key=await crypto.subtle.importKey('raw',hotfixB64urlBytes(keyText),{name:'AES-GCM'},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:hotfixB64urlBytes(payload.iv),additionalData:new TextEncoder().encode(payload.aad)},key,hotfixB64urlBytes(payload.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
function normalizeConsultant(c){return{...c,phone:c.phone||'',leader:c.leader||'',group:c.group||'',district:c.district||state.workspace?.distribution||'Vitoriaware',registrationStatus:c.registrationStatus||((String(c.status||'').toUpperCase()==='INATIVA')?'H / RECADASTRAR':'ATIVA')}}
function hotfixMergeConsultants(incoming){const existing=new Set(state.consultants.map(c=>`${String(c.code||'').trim()}|${String(c.name||'').trim().toLowerCase()}`));let added=0;for(const raw of incoming){const c=normalizeConsultant(raw),identity=`${String(c.code||'').trim()}|${String(c.name||'').trim().toLowerCase()}`;if(existing.has(identity))continue;state.consultants.push(c);existing.add(identity);added++}return added}
async function recoverTeamImport(){const key=getTeamImportKey();if(!key||typeof isSignedIn!=='function'||!isSignedIn())return false;if(state.consultants.length>0&&!location.hash.includes('team='))return true;try{const data=await hotfixDecryptTeam(key);if(!data||!Array.isArray(data.consultants)||!data.consultants.length)throw new Error('Payload vazio');const added=hotfixMergeConsultants(data.consultants);save();localStorage.setItem('voetupper-team-imported-v2','1');sessionStorage.removeItem(HOTFIX_TEAM_KEY);sessionStorage.removeItem('voetupper-team-import-key-v1');history.replaceState(null,'',location.pathname+location.search);render();setTimeout(()=>alert(`${state.consultants.length} consultoras disponíveis${added?` · ${added} importadas agora`:''}.`),40);return true}catch(err){console.error(err);return false}}

function copyValue(value,label='Dado'){if(!value)return;navigator.clipboard.writeText(String(value)).then(()=>toast(`${label} copiado`)).catch(()=>prompt(`Copie o ${label.toLowerCase()}:`,value))}
function toast(text){let t=document.getElementById('vtToast');if(!t){t=document.createElement('div');t.id='vtToast';t.className='vt-toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(window.__vtToast);window.__vtToast=setTimeout(()=>t.classList.remove('show'),1400)}
function hierarchyLabel(c){return[c.district,c.group,c.leader].filter(Boolean).join(' › ')}
function registrationClass(c){return String(c.registrationStatus||c.status||'').toUpperCase().includes('H')?'revisar':String(c.status||'').toLowerCase()}

teamView=function(){const active=state.consultants.filter(c=>c.status!=='INATIVA').length;const recad=state.consultants.filter(c=>String(c.registrationStatus||'').toUpperCase().includes('H')).length;return `<section class="panel team-panel"><div class="team-titlebar"><div><div class="eyebrow">EQUIPE · ESTRUTURA OPERACIONAL</div><h2>${state.consultants.length} consultoras <span>${active} ativas</span></h2></div><div class="team-title-actions"><button class="btn" onclick="toggleHierarchy()">Árvore</button><button class="btn primary" onclick="openConsultantCard()">+ Consultora</button></div></div><div class="team-kpis"><div><strong>${active}</strong><span>Ativas</span></div><div><strong>${stats().noOrder}</strong><span>Sem pedido na semana</span></div><div><strong>${recad}</strong><span>H / recadastrar</span></div></div><div id="hierarchyPanel"></div><div class="team-toolbar"><input class="search" id="teamSearch" placeholder="Buscar por nome, código, líder, grupo ou telefone" oninput="renderTeamRows(this.value)"></div><div class="team-columns"><span>Consultora</span><span>Código</span><span>Cadastro</span><span>Ações</span></div><div id="teamRows">${teamRows('')}</div></section>`}
teamRows=function(q){const needle=q.trim().toLowerCase();const list=state.consultants.map(normalizeConsultant).filter(c=>!needle||[c.name,c.code,c.phone,c.leader,c.group,c.district].some(v=>String(v||'').toLowerCase().includes(needle)));return list.length?list.map(c=>`<div class="team-row" onclick="openConsultantCard('${c.id}')"><div class="team-person"><span class="avatar">${esc(initials(c.name))}</span><div><strong>${esc(c.name)}</strong><small>${esc(hierarchyLabel(c)||'Grupo/líder ainda não informado')}</small></div></div><div class="copy-cell"><span class="team-code">${esc(c.code||'—')}</span>${c.code?`<button class="copy-btn" title="Copiar código" onclick="event.stopPropagation();copyValue('${esc(c.code)}','Código')">⧉</button>`:''}</div><span><b class="state-pill ${registrationClass(c)}">${esc(c.registrationStatus||c.status||'ATIVA')}</b></span><div class="team-actions">${c.phone?`<a class="mini" href="https://wa.me/55${c.phone.replace(/\D/g,'')}" target="_blank" rel="noopener" onclick="event.stopPropagation()">WhatsApp</a>`:''}<button class="mini" onclick="event.stopPropagation();openOrderForConsultant('${c.id}')">Pedido</button><button class="mini" onclick="event.stopPropagation();openConsultantCard('${c.id}')">Ficha</button></div></div>`).join(''):`<div class="queue-empty"><strong>Nenhuma consultora encontrada.</strong>Revise a busca.</div>`}
window.renderTeamRows=function(q){const el=document.getElementById('teamRows');if(el)el.innerHTML=teamRows(q)}
window.openOrderForConsultant=function(id){openOrder();setTimeout(()=>{const el=document.getElementById('oConsultant');if(el)el.value=id},0)}

window.toggleHierarchy=function(){const el=document.getElementById('hierarchyPanel');if(!el)return;if(el.innerHTML){el.innerHTML='';return}const grouped={};state.consultants.map(normalizeConsultant).forEach(c=>{const leader=c.leader||'Sem líder informada',group=c.group||'Sem grupo';grouped[leader]??={};grouped[leader][group]??=[];grouped[leader][group].push(c)});el.innerHTML=`<div class="hierarchy"><div class="hierarchy-root"><strong>${esc(state.workspace.distribution||'Distrito')}</strong><span>${esc(state.workspace.name||'Empresária')}</span></div>${Object.entries(grouped).map(([leader,groups])=>`<details open><summary>${esc(leader)} <b>${Object.values(groups).flat().length}</b></summary>${Object.entries(groups).map(([group,people])=>`<div class="hier-group"><strong>${esc(group)}</strong><span>${people.map(p=>`<button onclick="openConsultantCard('${p.id}')">${esc(p.name)}</button>`).join('')}</span></div>`).join('')}</details>`).join('')}</div>`}

window.openConsultantCard=function(id=''){const existing=state.consultants.find(c=>c.id===id);const c=normalizeConsultant(existing||{id:'',name:'',code:'',phone:'',status:'ATIVA'});modal=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><section class="modal consultant-card"><div class="modal-head"><div><div class="eyebrow">FICHA DA CONSULTORA</div><h2>${existing?esc(c.name):'Nova consultora'}</h2></div><button class="icon-close" onclick="closeModal()">×</button></div><form id="consultantForm" onsubmit="saveConsultantCard(event,'${esc(c.id)}')"><div class="form-grid"><div class="field wide"><label>Nome</label><input id="cName" value="${esc(c.name)}" required></div><div class="field"><label>Código Tupper.NET</label><div class="input-copy"><input id="cCode" value="${esc(c.code)}"><button type="button" onclick="copyValue(document.getElementById('cCode').value,'Código')">Copiar</button></div></div><div class="field"><label>Telefone / WhatsApp</label><input id="cPhone" value="${esc(c.phone)}"></div><div class="field"><label>Situação</label><select id="cStatus"><option ${c.status==='ATIVA'?'selected':''}>ATIVA</option><option ${c.status==='INATIVA'?'selected':''}>INATIVA</option><option ${c.status==='REVISAR'?'selected':''}>REVISAR</option></select></div><div class="field"><label>Cadastro no portal</label><select id="cReg"><option ${c.registrationStatus==='ATIVA'?'selected':''}>ATIVA</option><option ${String(c.registrationStatus).includes('H')?'selected':''}>H / RECADASTRAR</option><option ${c.registrationStatus==='NOVO CADASTRO'?'selected':''}>NOVO CADASTRO</option></select></div><div class="field"><label>Distrito / distribuição</label><input id="cDistrict" value="${esc(c.district)}"></div><div class="field"><label>Grupo</label><input id="cGroup" value="${esc(c.group)}" placeholder="Nome do grupo"></div><div class="field"><label>Líder responsável</label><input id="cLeader" value="${esc(c.leader)}" placeholder="Nome da líder"></div></div><div class="credential-box"><div><strong>Acesso ao Tupper.NET</strong><span>A senha não será colocada no GitHub nem exposta nesta versão pública. O campo entra quando o cofre privado estiver conectado.</span></div><button type="button" class="btn" disabled>Senha protegida</button></div><div class="modal-actions">${existing?`<button type="button" class="btn" onclick="openOrderForConsultant('${c.id}');closeModal()">Novo pedido</button>`:''}<button class="btn primary">Salvar ficha</button></div></form></section></div>`;render()}
window.saveConsultantCard=function(e,id){e.preventDefault();const data={name:document.getElementById('cName').value.trim(),code:document.getElementById('cCode').value.trim(),phone:document.getElementById('cPhone').value.trim(),status:document.getElementById('cStatus').value,registrationStatus:document.getElementById('cReg').value,district:document.getElementById('cDistrict').value.trim(),group:document.getElementById('cGroup').value.trim(),leader:document.getElementById('cLeader').value.trim()};if(id){const i=state.consultants.findIndex(c=>c.id===id);state.consultants[i]={...state.consultants[i],...data}}else state.consultants.push({...data,id:crypto.randomUUID()});save();modal=null;view='team';render();toast('Ficha salva')}

recoverTeamImport();let hotfixAttempts=0;const hotfixTimer=setInterval(async()=>{hotfixAttempts++;if(await recoverTeamImport()||hotfixAttempts>120)clearInterval(hotfixTimer)},500);
