const TEAM_IMPORT_SESSION_KEY='voetupper-team-import-key-v1';
const TEAM_IMPORT_MARKER='voetupper-team-imported-v1';
function b64urlBytes(value){const pad='='.repeat((4-value.length%4)%4);const bin=atob(value.replace(/-/g,'+').replace(/_/g,'/')+pad);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
function captureImportKey(){const match=location.hash.match(/(?:^#|&)team=([^&]+)/);if(!match)return;sessionStorage.setItem(TEAM_IMPORT_SESSION_KEY,decodeURIComponent(match[1]));history.replaceState(null,'',location.pathname+location.search)}
async function decryptTeam(keyText){const response=await fetch('./team.enc.json?v=1',{cache:'no-store'});if(!response.ok)throw new Error('Não foi possível carregar a equipe.');const payload=await response.json();const key=await crypto.subtle.importKey('raw',b64urlBytes(keyText),{name:'AES-GCM'},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64urlBytes(payload.iv),additionalData:new TextEncoder().encode(payload.aad)},key,b64urlBytes(payload.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
function mergeConsultants(incoming){const existing=new Set(state.consultants.map(c=>`${String(c.code||'').trim()}|${String(c.name||'').trim().toLowerCase()}`));let added=0;for(const c of incoming){const key=`${String(c.code||'').trim()}|${String(c.name||'').trim().toLowerCase()}`;if(existing.has(key))continue;state.consultants.push(c);existing.add(key);added++}return added}
async function maybeImportTeam(){const importKey=sessionStorage.getItem(TEAM_IMPORT_SESSION_KEY);if(!importKey||localStorage.getItem(TEAM_IMPORT_MARKER)==='1'||typeof isSignedIn!=='function'||!isSignedIn())return false;try{const data=await decryptTeam(importKey);if(!data||!Array.isArray(data.consultants))throw new Error('Equipe inválida.');const added=mergeConsultants(data.consultants);save();localStorage.setItem(TEAM_IMPORT_MARKER,'1');sessionStorage.removeItem(TEAM_IMPORT_SESSION_KEY);render();setTimeout(()=>alert(`${added} consultoras importadas da planilha operacional.`),30);return true}catch(err){console.error('VoeTupper team import failed',err);return false}}
captureImportKey();
let attempts=0;const importTimer=setInterval(async()=>{attempts++;if(await maybeImportTeam()||attempts>240)clearInterval(importTimer)},500);
