'use client';
import { useMemo,useState } from 'react';
import { buildTodaySummary } from '@/lib/domain/dashboard';
import { isTerminal,nextActionLabel,nextOrderStage } from '@/lib/domain/order';
import type { Consultant,Offer,Order,SourceChannel,Week } from '@/lib/domain/types';

type Tab='today'|'orders'|'closing'|'team';
const week:Week={id:'week-demo',label:'Semana atual',campaignId:'campaign-demo',closesAt:'2026-08-31T20:00:00-03:00',teamGoal:5000,status:'ACTIVE'};
const offers:Offer[]=[{id:'off1',title:'Cadastre aqui o incentivo da semana',weekId:week.id,active:true}];
const initialConsultants:Consultant[]=[{id:'c1',name:'Consultora exemplo',businessCode:'000001',status:'ACTIVE'}];
const initialOrders:Order[]=[];
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);

export default function OperationsApp(){
 const [tab,setTab]=useState<Tab>('today'); const [consultants,setConsultants]=useState(initialConsultants); const [orders,setOrders]=useState(initialOrders); const [newOrder,setNewOrder]=useState(false); const [newPerson,setNewPerson]=useState(false);
 const summary=useMemo(()=>buildTodaySummary({week,orders,consultants,offers}),[orders,consultants]);
 const advance=(id:string)=>setOrders(xs=>xs.map(o=>o.id===id?{...o,stage:nextOrderStage(o.stage)??o.stage}:o));
 const pending=orders.filter(o=>!isTerminal(o.stage));
 const person=(id:string)=>consultants.find(c=>c.id===id)?.name??'Consultora';
 return <><div className="app"><header className="top"><div><div className="brand">Voa</div><div className="eyebrow">operação de vendas</div></div><div className="cycle">{week.label}</div></header>
 {tab==='today'&&<><section className="hero"><div className="eyebrow">Agora</div><h1>{summary.pendingCount?`${summary.pendingCount} pedido${summary.pendingCount>1?'s':''} precisa de você`:'Tudo sob controle'}</h1><p>{summary.pendingCount?'Resolva a fila; o que for concluído desaparece daqui.':'Quando chegar um pedido, registre em poucos segundos.'}</p><button className="primary" onClick={()=>setNewOrder(true)}>+ Novo pedido</button></section><div className="metrics"><div className="metric"><strong>{summary.pendingCount}</strong><span>pendentes</span></div><div className="metric"><strong>{summary.portalPendingCount}</strong><span>para portal</span></div><div className="metric"><strong>{summary.confirmationPendingCount}</strong><span>confirmar</span></div><div className="metric"><strong>{summary.noOrderCount}</strong><span>sem pedido concluído</span></div></div><section className="card"><div className="row"><div><div className="eyebrow">Produção da semana</div><div className="money">{money(summary.realized)}</div></div><strong>{Math.round(summary.progress*100)}%</strong></div><div className="progress"><i style={{width:`${Math.min(100,summary.progress*100)}%`}}/></div><small>Meta {money(summary.goal)}</small></section><section className="section"><div className="sectionhead"><h2>Faça agora</h2><button className="action" onClick={()=>setTab('closing')}>Ver fechamento</button></div><Queue orders={pending.slice(0,3)} person={person} advance={advance}/></section><section className="section"><h2>Incentivos</h2><div className="stack">{summary.activeOffers.map(o=><div className="card" key={o.id}>{o.title}</div>)}</div></section></>}
 {tab==='orders'&&<><div className="sectionhead"><div><div className="eyebrow">Histórico</div><h1>Pedidos</h1></div><button className="action" onClick={()=>setNewOrder(true)}>+ Novo</button></div><div className="chips"><button className="chip">Todos</button><button className="chip" onClick={()=>setTab('closing')}>Só pendentes ({pending.length})</button></div><div className="section stack">{orders.length?orders.map(o=><OrderCard key={o.id} order={o} name={person(o.consultantId)} advance={advance}/>):<div className="empty">Nenhum pedido ainda.</div>}</div></>}
 {tab==='closing'&&<><div className="sectionhead"><div><div className="eyebrow">Semana atual</div><h1>Fechamento</h1></div><strong>{pending.length} aberto{pending.length===1?'':'s'}</strong></div><p style={{color:'var(--muted)'}}>Só aparece o que ainda exige ação.</p><div className="stack">{pending.length?<Queue orders={pending} person={person} advance={advance}/>:<div className="empty card">Fila zerada. Nada para perseguir.</div>}</div><a className="primary" style={{display:'grid',placeItems:'center',textDecoration:'none'}} href="https://www.tupperware.com.br/" target="_blank" rel="noreferrer">Abrir portal da empresa ↗</a></>}
 {tab==='team'&&<><div className="sectionhead"><div><div className="eyebrow">Pessoas</div><h1>Equipe</h1></div><button className="action" onClick={()=>setNewPerson(true)}>+ Consultora</button></div><div className="stack">{consultants.map(c=><div className="card row" key={c.id}><main><strong>{c.name}</strong><small>{c.businessCode?`Código ${c.businessCode} · `:''}{statusLabel(c.status)}</small></main>{c.phone&&<a className="link" href={`https://wa.me/${c.phone.replace(/\D/g,'')}`}>WhatsApp</a>}</div>)}</div></>}
 </div><nav className="nav" aria-label="Navegação principal"><div className="navinner">{([['today','Hoje'],['orders','Pedidos'],['closing','Fechamento'],['team','Equipe']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} aria-current={tab===id}>{label}</button>)}</div></nav>
 {newOrder&&<OrderSheet consultants={consultants.filter(c=>c.status==='ACTIVE'||c.status==='NEW')} onClose={()=>setNewOrder(false)} onSave={o=>{setOrders(xs=>[o,...xs]);setNewOrder(false);setTab('today')}}/>}
 {newPerson&&<PersonSheet onClose={()=>setNewPerson(false)} onSave={c=>{setConsultants(xs=>[...xs,c]);setNewPerson(false)}}/>}</>;
}
function Queue({orders,person,advance}:{orders:Order[];person:(id:string)=>string;advance:(id:string)=>void}){return <div className="stack">{orders.length?orders.map(o=><OrderCard key={o.id} order={o} name={person(o.consultantId)} advance={advance}/>):<div className="empty">Nenhuma ação pendente.</div>}</div>}
function OrderCard({order,name,advance}:{order:Order;name:string;advance:(id:string)=>void}){return <div className="card row"><main><strong>{name}</strong><small>{order.summary}{order.amount!=null?` · ${money(order.amount)}`:''}</small></main>{!isTerminal(order.stage)&&<button className="action" onClick={()=>advance(order.id)}>{nextActionLabel(order.stage)}</button>}</div>}
function OrderSheet({consultants,onClose,onSave}:{consultants:Consultant[];onClose:()=>void;onSave:(o:Order)=>void}){const [consultantId,setConsultant]=useState(consultants[0]?.id??'');const [source,setSource]=useState<SourceChannel>('TEXT');const [summary,setSummary]=useState('');const [amount,setAmount]=useState('');return <div className="sheet" role="dialog" aria-modal="true"><form className="sheetbox" onSubmit={e=>{e.preventDefault();if(!consultantId||!summary.trim())return;onSave({id:crypto.randomUUID(),consultantId,weekId:week.id,source,summary:summary.trim(),amount:amount?Number(amount):undefined,stage:'RECEIVED',createdAt:new Date().toISOString()})}}><div className="sheettitle"><div><div className="eyebrow">{week.label}</div><h2>Novo pedido</h2></div><button type="button" className="iconbtn" onClick={onClose} aria-label="Fechar">×</button></div><div className="field"><label>Consultora</label><select value={consultantId} onChange={e=>setConsultant(e.target.value)} required>{consultants.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Chegou como</label><select value={source} onChange={e=>setSource(e.target.value as SourceChannel)}><option value="TEXT">Texto</option><option value="AUDIO">Áudio</option><option value="PHOTO">Foto</option><option value="OTHER">Outro</option></select></div><div className="field"><label>Resumo do pedido</label><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Ex.: 2 potes + 1 garrafa" required/></div><div className="field"><label>Valor, se souber</label><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value.replace(',','.'))} placeholder="0,00"/></div><button className="primary">Salvar pedido</button></form></div>}
function PersonSheet({onClose,onSave}:{onClose:()=>void;onSave:(c:Consultant)=>void}){const [name,setName]=useState('');const [code,setCode]=useState('');const [phone,setPhone]=useState('');return <div className="sheet" role="dialog" aria-modal="true"><form className="sheetbox" onSubmit={e=>{e.preventDefault();if(name.trim().length<2)return;onSave({id:crypto.randomUUID(),name:name.trim(),businessCode:code||undefined,phone:phone||undefined,status:'ACTIVE'})}}><div className="sheettitle"><h2>Nova consultora</h2><button type="button" className="iconbtn" onClick={onClose}>×</button></div><div className="field"><label>Nome</label><input value={name} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label>Código, se usar</label><input value={code} onChange={e=>setCode(e.target.value)}/></div><div className="field"><label>Telefone, opcional</label><input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></div><button className="primary">Adicionar à equipe</button></form></div>}
function statusLabel(s:Consultant['status']){return ({ACTIVE:'Ativa',NEW:'Nova',PAUSED:'Pausada',INACTIVE:'Inativa'} as const)[s]}
