import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');const css=readFileSync(new URL('../app.css',import.meta.url),'utf8');const js=readFileSync(new URL('../app.js',import.meta.url),'utf8');const hotfix=readFileSync(new URL('../hotfix.js',import.meta.url),'utf8');const product=readFileSync(new URL('../product-v6.js',import.meta.url),'utf8');const network=readFileSync(new URL('../network-es.js',import.meta.url),'utf8');const networkCss=readFileSync(new URL('../network-es.css',import.meta.url),'utf8');const pilotDisplay=readFileSync(new URL('../pilot-display.js',import.meta.url),'utf8');const bundle=`${html}\n${css}\n${js}\n${hotfix}\n${product}\n${network}\n${networkCss}\n${pilotDisplay}`;const activeProduct=`${html}\n${product}\n${network}\n${pilotDisplay}`;
describe('VoeTupper pilot',()=>{
it('keeps operational shell',()=>{expect(html).toContain('O que precisa ser resolvido');expect(js).toContain("week:'36/2026',vitrine:'09/2026'");expect(hotfix).toContain("w35.vitrine='09/2026'")});
it('preserves auth and storage',()=>{expect(js).toContain("const STATE_KEY='voetupper-vitoriaware-state-v1'");expect(js).toContain("const AUTH_KEY='voetupper-vitoriaware-auth-v1'");expect(js).toContain("const SESSION_KEY='voetupper-vitoriaware-session-v1'");expect(pilotDisplay).not.toContain('localStorage')});
it('keeps portal credentials protected but operational',()=>{expect(product).toContain('portalPassword');expect(product).toContain('Mostrar');expect(product).toContain('Copiar senha');expect(product).toContain('Copiar código')});
it('models Grupo Fenomenal',()=>{for(const copy of ['Ritheli Radis','Grupo Fenomenal','Fenomenal'])expect(bundle).toContain(copy);expect(network).toContain('vt8RitheliBranch')});
it('renders operational consultant cards',()=>{expect(network).toContain("'114440':{name:'Adriana Vieira',status:'INATIVA'}");for(const copy of ['Código','Senha do portal','Fechamento','ATIVA','INATIVA','DADOS A CONFERIR'])expect(network).toContain(copy);expect(network).toContain('vt10ConsultantCard');expect(network).toContain('vt10StatusClass')});
it('separates linked active and inactive counts',()=>{expect(network).toContain('vinculadas');expect(network).toContain('ativas');expect(network).toContain('inativa')});
it('renders approved logo as direct JPEG data URL',()=>{expect(pilotDisplay).toContain("const VT9_APPROVED_LOGO='data:image/jpeg;base64,");expect(pilotDisplay).not.toContain("brandImg.src='./logo.svg?v=9'");expect(networkCss).toContain('.brand-row>img')});
it('keeps pink responsive UI',()=>{expect(css).toContain('--pink:#e91e63');expect(networkCss).toContain('.vt7-mobile-nav');expect(networkCss).toContain('@media')});
it('avoids em dash',()=>{expect(activeProduct).not.toContain('—')});
it('scripts parse',()=>{expect(()=>new Function(js)).not.toThrow();expect(()=>new Function(hotfix)).not.toThrow();expect(()=>new Function(product)).not.toThrow();expect(()=>new Function(network)).not.toThrow();expect(()=>new Function(pilotDisplay)).not.toThrow()});
});
